# -*- coding: utf-8 -*-
from . import qualifica
from . import ruolo
from . import tipo_cert_volontario
from . import tipo_cert_attrezzatura
from . import tipo_contratto
from . import certificazione_volontario
from . import certificazione_attrezzatura
from . import hr_employee
from . import fleet_vehicle
from . import maintenance_equipment
from . import contratto_rata
from . import contratto
from . import intervento_squadra
from . import intervento_paziente
from . import intervento_consenso
from . import tipo_intervento
from . import intervento
from . import tipo_esercitazione
from . import esercitazione
from . import turno_squadra
from . import turno
from . import turno_report_wizard
from . import codice_fiscale_wizard
